### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kendalor** [artheus/feedthebeast-docker-servers#1]
Hi there, 
how do you intent to update running containers ? 
If i attach to the container and stop the server the whole container closes. 
Got any Tips ? 

Regards
Kendalor

**Comment by artheus** [comment]
That is the expected behaviour of Docker. The docker container runs for as long as the process runs. So if you want to stop it you can stop it using the stop command, and restart it using `docker start containername` which will start it up again.
Explain more on how you would expect it to behave, please.

I could use systemd to look out for the process, and use systemd as the main running process. This would then let you control the server process without having to stop the container when you execute the stop command on the MC server.
But what would really be the benefit of that in this case. Please explain it to me.
Thank you.
